In [1]:
# pip installer
!pip install nflreadpy
!pip install pandas
!pip install polars
!pip install sklearn

Collecting nflreadpy
  Downloading nflreadpy-0.1.5-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: requests>=2.28.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (2.32.4)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (1.31.0)
Requirement already satisfied: platformdirs>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (4.5.1)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (4.67.1)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from nflreadpy) (2.12.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->nflreadpy) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0.0->nflreadpy) (1.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.0->nflreadpy) (2025.11.12)
Downloading nflreadpy-0.1.5-py3-none-any.whl (30 kB)
Installing collected packages: nflreadpy
Successfully installed nflreadpy-0.1.5
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: polars in /usr/local/lib/python3.12/dist-packages (1.31.0)
Collecting sklearn
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [ ]:
# Import libraries
import nflreadpy as nfl
import pandas as pd
import polars as pl


from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, log_loss, roc_auc_score

In [3]:
## Load data 
seasons = list(range(2018, 2025)) # Slicing to the last 7-sevens
pbp = nfl.load_pbp(seasons=seasons)

In [ ]:
# Showing the first 5-lines
pbp.head()

shape: (5, 372)
┌─────────┬────────────┬────────────┬───────────┬───┬────────────┬──────────┬──────────┬───────────┐
│ play_id ┆ game_id    ┆ old_game_i ┆ home_team ┆ … ┆ xyac_succe ┆ xyac_fd  ┆ xpass    ┆ pass_oe   │
│ ---     ┆ ---        ┆ d          ┆ ---       ┆   ┆ ss         ┆ ---      ┆ ---      ┆ ---       │
│ f64     ┆ str        ┆ ---        ┆ str       ┆   ┆ ---        ┆ f64      ┆ f64      ┆ f64       │
│         ┆            ┆ str        ┆           ┆   ┆ f64        ┆          ┆          ┆           │
╞═════════╪════════════╪════════════╪═══════════╪═══╪════════════╪══════════╪══════════╪═══════════╡
│ 1.0     ┆ 2018_01_AT ┆ 2018090600 ┆ PHI       ┆ … ┆ null       ┆ null     ┆ null     ┆ null      │
│         ┆ L_PHI      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 37.0    ┆ 2018_01_AT ┆ 2018090600 ┆ PHI       ┆ … ┆ null       ┆ null     ┆ null     ┆ null      │
│         ┆ L_PHI      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 52.0    ┆ 2018_01_AT ┆ 2018090600 ┆ PHI       ┆ … ┆ null       ┆ null     ┆ 0.479781 ┆ null      │
│         ┆ L_PHI      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 75.0    ┆ 2018_01_AT ┆ 2018090600 ┆ PHI       ┆ … ┆ 0.998706   ┆ 0.147457 ┆ 0.587117 ┆ 41.288257 │
│         ┆ L_PHI      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 104.0   ┆ 2018_01_AT ┆ 2018090600 ┆ PHI       ┆ … ┆ null       ┆ null     ┆ 0.498259 ┆ -49.82591 │
│         ┆ L_PHI      ┆            ┆           ┆   ┆            ┆          ┆          ┆ 3         │
└─────────┴────────────┴────────────┴───────────┴───┴────────────┴──────────┴──────────┴───────────┘

In [ ]:
pbp.shape() # Printing the shape of the Polars dataframe

In [ ]:
# Getting a better understanding what EPA is
pbp.select("epa").describe()

shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ epa        │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 336684.0   │
│ null_count ┆ 3903.0     │
│ mean       ┆ -0.005973  │
│ std        ┆ 1.258912   │
│ min        ┆ -13.584859 │
│ 25%        ┆ -0.5609    │
│ 50%        ┆ 0.0        │
│ 75%        ┆ 0.526099   │
│ max        ┆ 8.882384   │
└────────────┴────────────┘

In [21]:
pbp.select("play_type").unique() # What is inside the play_type column

shape: (10, 1)
┌─────────────┐
│ play_type   │
│ ---         │
│ str         │
╞═════════════╡
│ qb_spike    │
│ extra_point │
│ qb_kneel    │
│ run         │
│ no_play     │
│ pass        │
│ punt        │
│ kickoff     │
│ null        │
│ field_goal  │
└─────────────┘

In [ ]:
pbp.select("season_type").unique()
# since there is only post and regular, we keep both of them

shape: (2, 1)
┌─────────────┐
│ season_type │
│ ---         │
│ str         │
╞═════════════╡
│ POST        │
│ REG         │
└─────────────┘

In [24]:
# Keeping the plays where EPA is not null
pbp = pbp.filter(
    (pl.col("epa").is_not_null()) &
    (pl.col("play_type").is_in(["run","pass"]))  # removing qb_kneels, field goals and so forth
)

In [ ]:
pbp.shape # printing the new shape of the dataframe

(242888, 372)

In [ ]:
# Team-game aggregations from the pbp
## Computing offensive efficiency per team per game

team_game = ( 
    pbp.group_by(["seaon", "week", "game_id", "postteam"])
    .agg([
        pl.mean("epa").alias("off_epa_per_play"), # storing mean of epa as off_epa_per_play
        (pl.col("epa") > 0).mean().alias("off_success_rate"), # Storing the offensive success rate where the EPA is increased
        (pl.col("play_type") == "pass").mean().alias("off_pass_rate"), # storing the success for play type pass
        (pl.col("play_type") == "run").mean().alias("off_run_ra te"),
        pl.count().alias("off_plays") # number of offensive plays
    ])
    .rename({"posteam":"team"})
)

In [18]:
pbp.select("wpa").head()

shape: (5, 1)
┌───────────┐
│ wpa       │
│ ---       │
│ f64       │
╞═══════════╡
│ -0.0      │
│ -0.0      │
│ -0.022318 │
│ 0.009866  │
│ 0.034143  │
└───────────┘